# Generated by Django 3.2.18 on 2023-04-24 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LineItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("score_maximum", models.IntegerField()),
                ("label", models.CharField(max_length=255)),
                ("resource_id", models.CharField(max_length=255)),
                ("tag", models.CharField(max_length=255, null=True)),
                ("resource_link_id", models.CharField(max_length=255, null=True)),
                ("start_date_time", models.DateTimeField(null=True)),
                ("end_date_time", models.DateTimeField(null=True)),
                ("grades_released", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_given", models.IntegerField()),
                ("score_maximum", models.IntegerField(null=True)),
                ("comment", models.CharField(max_length=255, null=True)),
                ("activity_progress", models.CharField(max_length=255)),
                ("grading_progress", models.CharField(max_length=255)),
                ("userId", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("submission_started_at", models.DateTimeField(null=True)),
                ("submission_ended_at", models.DateTimeField(null=True)),
                (
                    "lineItem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ags.lineitem"
                    ),
                ),
            ],
        ),
    ]
