# Generated by Django 3.2.18 on 2023-04-24 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scoreMaximum', models.IntegerField()),
                ('label', models.CharField(max_length=255)),
                ('resourceId', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255, null=True)),
                ('resourceLinkId', models.CharField(max_length=255, null=True)),
                ('startDateTime', models.DateTimeField(null=True)),
                ('endDateTime', models.DateTimeField(null=True)),
                ('gradesReleased', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreGiven', models.IntegerField()),
                ('scoreMaximum', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('activityProgress', models.CharField(max_length=255)),
                ('gradingProgress', models.CharField(max_length=255)),
                ('userId', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('submissionStartedAt', models.DateTimeField(null=True)),
                ('submissionEndedAt', models.DateTimeField(null=True)),
                ('lineItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ags.lineitem')),
            ],
        ),
    ]
